### ISSUE TITLE
update databricks init script

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids-examples#104]
if there are already xgboost jars in dbfs, we will run into some issues, we need to remove them from the init script.

**Comment by viadea** [comment]
As per doc: https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.02/docs/get-started/xgboost-examples/csp/databricks/databricks.md, we just need to add the 2 xgboost4j related jars through "Libraries" section.
However it will cause issue due to the conflict from existing 2 xgboost4j jars in databricks by default:

Just run below in notebook after init a Databricks 9.1ML GPU:
```
%sh
ls -altr /databricks/jars|grep -i xgboost4j
```

Below 2 jars are there out of the box:
```
-r-xr-xr-x 1 root root    276203 Jan  1  1970 spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-spark-gpu_2.12--ml.dmlc__xgboost4j-spark-gpu_2.12__1.4.1.jar
-r-xr-xr-x 1 root root 167074071 Jan  1  1970 spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-gpu_2.12--ml.dmlc__xgboost4j-gpu_2.12__1.4.1.jar
```

As a result, to workaround this issue, we have to remove those 2 jars in init script, then it works fine:
```
rm -f /databricks/jars/spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-spark-gpu_2.12--ml.dmlc__xgboost4j-spark-gpu_2.12__1.4.1.jar
rm -f /databricks/jars/spark--maven-trees--ml--9.x--xgboost-gpu--ml.dmlc--xgboost4j-gpu_2.12--ml.dmlc__xgboost4j-gpu_2.12__1.4.1.jar
```

**Comment by nvliyuan** [comment]
Thanks @chrisVietDev for the codes, since we have already overwritten the xbgoost jars in [init script](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.02/docs/get-started/xgboost-examples/csp/databricks/generate-init-script.ipynb), it should also work, can you please try it?

**Comment by nvliyuan** [comment]
verified the init script, it works, so close this issue

**Comment by viadea** [comment]
@nvliyuan  have we updated the gen-init scripts for this?thx
